In [1]:
!pip install numpy
!pip install pandas
!pip install openpyxl

Requirement already satisfied: numpy in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (2.3.5)

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (2.3.3)

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install spicy

Requirement already satisfied: spicy in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (0.16.0)
Requirement already satisfied: scipy in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from spicy) (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in c:\users\asus\onedrive\desktop\pto\credit-risk-modeling\myenvi\lib\site-packages (from scipy->spicy) (2.3.5)

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
a1 = pd.read_excel("./data/case_study1.xlsx")
a2 = pd.read_excel("./data/case_study2.xlsx")

In [6]:
df1 = a1.copy()
df2 = a2.copy()

In [7]:
df1.describe()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
count,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,...,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000
mean,25668.500000,4.858598,2.770415,2.088184,0.736754,0.428919,0.184574,0.089095,0.577542,0.422458,...,0.124981,1.136084,1.561847,0.070146,0.282511,2.844904,2.013694,1.089762,-32.575639,-62.149525
std,14819.571046,7.177116,5.941680,2.290774,1.296717,0.989972,0.297414,0.205635,0.379867,0.379867,...,0.505201,2.227997,5.376434,0.340861,0.858168,6.187177,3.198322,2.417496,2791.869609,2790.818622
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,-99999.000000
25%,12834.750000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,4.000000
50%,25668.500000,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.556000,0.444000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,33.000000,8.000000
75%,38502.250000,5.000000,3.000000,3.000000,1.000000,1.000000,0.308000,0.053000,1.000000,0.750000,...,0.000000,1.000000,1.000000,0.000000,0.000000,3.000000,2.000000,1.000000,64.000000,17.000000
max,51336.000000,235.000000,216.000000,47.000000,27.000000,19.000000,1.000000,1.000000,1.000000,1.000000,...,27.000000,41.000000,235.000000,10.000000,29.000000,235.000000,55.000000,80.000000,392.000000,392.000000

In [8]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [9]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

In [11]:
df1.shape

(51336, 26)

In [12]:
df1.isna().sum()

PROSPECTID              0
Total_TL                0
Tot_Closed_TL           0
Tot_Active_TL           0
Total_TL_opened_L6M     0
Tot_TL_closed_L6M       0
pct_tl_open_L6M         0
pct_tl_closed_L6M       0
pct_active_tl           0
pct_closed_tl           0
Total_TL_opened_L12M    0
Tot_TL_closed_L12M      0
pct_tl_open_L12M        0
pct_tl_closed_L12M      0
Tot_Missed_Pmnt         0
Auto_TL                 0
CC_TL                   0
Consumer_TL             0
Gold_TL                 0
Home_TL                 0
PL_TL                   0
Secured_TL              0
Unsecured_TL            0
Other_TL                0
Age_Oldest_TL           0
Age_Newest_TL           0
dtype: int64

In [13]:
df1.duplicated().sum()

0

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  object
 39  EDUCATION                     51336 non-null  object
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  object
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  object
 59  first_prod_enq2               51336 non-null  object
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  object
dtypes: float64(10), int64(46), object(6)
memory usage: 24.3+ MB

In [15]:
df2.isna().sum()

PROSPECTID                      0
time_since_recent_payment       0
time_since_first_deliquency     0
time_since_recent_deliquency    0
num_times_delinquent            0
                               ..
GL_Flag                         0
last_prod_enq2                  0
first_prod_enq2                 0
Credit_Score                    0
Approved_Flag                   0
Length: 62, dtype: int64

In [16]:
df2.shape

(51336, 62)

In [17]:
# removing nulls
df1.loc[df1["Age_Oldest_TL"]!=-99999]

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [18]:
columns_to_be_removed = []
for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        columns_to_be_removed.append(i)
columns_to_be_removed

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

In [19]:
df2.isna().sum()

PROSPECTID                      0
time_since_recent_payment       0
time_since_first_deliquency     0
time_since_recent_deliquency    0
num_times_delinquent            0
                               ..
GL_Flag                         0
last_prod_enq2                  0
first_prod_enq2                 0
Credit_Score                    0
Approved_Flag                   0
Length: 62, dtype: int64

In [20]:
df2 = df2.drop(columns_to_be_removed,axis=1)

In [21]:
df2.shape

(51336, 54)

In [22]:
for i in df2.columns:
    df2 = df2.loc[df2[i] != -99999]

In [23]:
df2.shape

(42066, 54)

In [24]:
df2.isna().sum()

PROSPECTID                    0
time_since_recent_payment     0
num_times_delinquent          0
max_recent_level_of_deliq     0
num_deliq_6mts                0
num_deliq_12mts               0
num_deliq_6_12mts             0
num_times_30p_dpd             0
num_times_60p_dpd             0
num_std                       0
num_std_6mts                  0
num_std_12mts                 0
num_sub                       0
num_sub_6mts                  0
num_sub_12mts                 0
num_dbt                       0
num_dbt_6mts                  0
num_dbt_12mts                 0
num_lss                       0
num_lss_6mts                  0
num_lss_12mts                 0
recent_level_of_deliq         0
tot_enq                       0
CC_enq                        0
CC_enq_L6m                    0
CC_enq_L12m                   0
PL_enq                        0
PL_enq_L6m                    0
PL_enq_L12m                   0
time_since_recent_enq         0
enq_L12m                      0
enq_L6m                       0
enq_L3m                       0
MARITALSTATUS                 0
EDUCATION                     0
AGE                           0
GENDER                        0
NETMONTHLYINCOME              0
Time_With_Curr_Empr           0
pct_of_active_TLs_ever        0
pct_opened_TLs_L6m_of_L12m    0
pct_currentBal_all_TL         0
CC_Flag                       0
PL_Flag                       0
pct_PL_enq_L6m_of_L12m        0
pct_CC_enq_L6m_of_L12m        0
pct_PL_enq_L6m_of_ever        0
pct_CC_enq_L6m_of_ever        0
HL_Flag                       0
GL_Flag                       0
last_prod_enq2                0
first_prod_enq2               0
Credit_Score                  0
Approved_Flag                 0
dtype: int64

In [25]:
for i in list(df1.columns):
    if i in list(df2.columns):
        print(i)

PROSPECTID

In [26]:
#merge two tables
df = pd.merge(df1,df2,how="inner",left_on=["PROSPECTID"],right_on=["PROSPECTID"])

In [27]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [28]:
df.shape

(42066, 79)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42066 entries, 0 to 42065
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  42066 non-null  int64
 1   Total_TL                    42066 non-null  int64
 2   Tot_Closed_TL               42066 non-null  int64
 3   Tot_Active_TL               42066 non-null  int64
 4   Total_TL_opened_L6M         42066 non-null  int64
 5   Tot_TL_closed_L6M           42066 non-null  int64
 6   pct_tl_open_L6M             42066 non-null  float64
 7   pct_tl_closed_L6M           42066 non-null  float64
 8   pct_active_tl               42066 non-null  float64
 9   pct_closed_tl               42066 non-null  float64
 10  Total_TL_opened_L12M        42066 non-null  int64
 11  Tot_TL_closed_L12M          42066 non-null  int64
 12  pct_tl_open_L12M            42066 non-null  float64
 13  pct_tl_closed_L12M          42066 non-null  float64
 14  Tot_Missed_Pmnt             42066 non-null  int64
 15  Auto_TL                     42066 non-null  int64
 16  CC_TL                       42066 non-null  int64
 17  Consumer_TL                 42066 non-null  int64
 18  Gold_TL                     42066 non-null  int64
 19  Home_TL                     42066 non-null  int64
 20  PL_TL                       42066 non-null  int64
 21  Secured_TL                  42066 non-null  int64
 22  Unsecured_TL                42066 non-null  int64
 23  Other_TL                    42066 non-null  int64
 24  Age_Oldest_TL               42066 non-null  int64
 25  Age_Newest_TL               42066 non-null  int64
 26  time_since_recent_payment   42066 non-null  int64
 27  num_times_delinquent        42066 non-null  int64
 28  max_recent_level_of_deliq   42066 non-null  int64
 29  num_deliq_6mts              42066 non-null  int64
 30  num_deliq_12mts             42066 non-null  int64
 31  num_deliq_6_12mts           42066 non-null  int64
 32  num_times_30p_dpd           42066 non-null  int64
 33  num_times_60p_dpd           42066 non-null  int64
 34  num_std                     42066 non-null  int64
 35  num_std_6mts                42066 non-null  int64
 36  num_std_12mts               42066 non-null  int64
 37  num_sub                     42066 non-null  int64
 38  num_sub_6mts                42066 non-null  int64
 39  num_sub_12mts               42066 non-null  int64
 40  num_dbt                     42066 non-null  int64
 41  num_dbt_6mts                42066 non-null  int64
 42  num_dbt_12mts               42066 non-null  int64
 43  num_lss                     42066 non-null  int64
 44  num_lss_6mts                42066 non-null  int64
 45  num_lss_12mts               42066 non-null  int64
 46  recent_level_of_deliq       42066 non-null  int64
 47  tot_enq                     42066 non-null  int64
 48  CC_enq                      42066 non-null  int64
 49  CC_enq_L6m                  42066 non-null  int64
 50  CC_enq_L12m                 42066 non-null  int64
 51  PL_enq                      42066 non-null  int64
 52  PL_enq_L6m                  42066 non-null  int64
 53  PL_enq_L12m                 42066 non-null  int64
 54  time_since_recent_enq       42066 non-null  int64
 55  enq_L12m                    42066 non-null  int64
 56  enq_L6m                     42066 non-null  int64
 57  enq_L3m                     42066 non-null  int64
 58  MARITALSTATUS               42066 non-null  object
 59  EDUCATION                   42066 non-null  object
 60  AGE                         42066 non-null  int64
 61  GENDER                      42066 non-null  object
 62  NETMONTHLYINCOME            42066 non-null  int64
 63  Time_With_Curr_Empr         42066 non-null  int64
 64  pct_of_active_TLs_ever      42066 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  42066 non-null  float64
 66  pct_currentBal_all_TL       42066 non-null  float64
 67  CC_Flag                     42066 non-null  int64
 68  PL_Flag                     42066 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      42066 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      42066 non-null  float64
 71  pct_PL_enq_L6m_of_ever      42066 non-null  float64
 72  pct_CC_enq_L6m_of_ever      42066 non-null  float64
 73  HL_Flag                     42066 non-null  int64
 74  GL_Flag                     42066 non-null  int64
 75  last_prod_enq2              42066 non-null  object
 76  first_prod_enq2             42066 non-null  object
 77  Credit_Score                42066 non-null  int64
 78  Approved_Flag               42066 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 25.4+ MB

In [30]:
df.isna().sum().sum()

0

In [31]:
for i in list(df.columns):
    if df[i].dtype == "object":
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [32]:
# feature selection
for i in ["MARITALSTATUS","EDUCATION","GENDER","last_prod_enq2","first_prod_enq2"]:
    chi2, p_val,_ , _ = chi2_contingency(pd.crosstab(df[i],df["Approved_Flag"]))
    print(i,"----",p_val)

MARITALSTATUS ---- 3.6401547776371343e-233
EDUCATION ---- 2.8651007585199264e-30
GENDER ---- 1.8610038357046495e-05
last_prod_enq2 ---- 0.0
first_prod_enq2 ---- 8.375872889007586e-287

In [33]:
numeric_columns = []

for i in df.columns:
    if df[i].dtype != "object" and i not in ["PROSPECTID","Approved_Flag"]:
        numeric_columns.append(i)

In [34]:
# VIF sequentiality check
vif_data = df[numeric_columns]
vif_data.shape[1]

72

In [35]:
vif_data = df[numeric_columns]
total_col = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0

for i  in range(0,total_col):
    vif_value = variance_inflation_factor(vif_data,column_index)
    print(column_index,"----",vif_value)

    if vif_value < 6:
        columns_to_be_kept.append(numeric_columns[i])
        column_index += 1
    else: 
        vif_data = vif_data.drop([numeric_columns[i]],axis =1)

C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 ---- inf

C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 ---- inf
0 ---- 11.319677860911183
0 ---- 8.291829772566755
0 ---- 6.520138234382173
0 ---- 5.059265701555735
1 ---- 2.6064779388021027

C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 ---- inf
2 ---- 1779.2530019989363
2 ---- 8.57605846135607
2 ---- 3.829565647163703
3 ---- 5.469211095570595
4 ---- 5.503957502932514
5 ---- 1.973712154119323

C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

6 ---- inf
6 ---- 4.811919298953732
7 ---- 23.146961044026003
7 ---- 30.634993848319926
7 ---- 4.384922735753695
8 ---- 3.0648663541161247
9 ---- 2.8932461784347443
10 ---- 4.369654303665843
11 ---- 2.208341258584075
12 ---- 566.1909055769335
12 ---- 1.0006593766842493
13 ---- 1.9695830645742571
14 ---- 7.841218783259259
14 ---- 5.247703415624753

C:\Users\ASUS\AppData\Roaming\Python\Python312\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 ---- inf
15 ---- 7.377956585088547
15 ---- 1.4257933668144418
16 ---- 8.084822288044927
16 ---- 1.622669921839381
17 ---- 7.238615905249871
17 ---- 15.645211505952748
17 ---- 1.8184084209088587
18 ---- 1.5055024528703038
19 ---- 2.172012934391218
20 ---- 2.6235392775473536
21 ---- 2.2929276257397038
22 ---- 7.358811901616798
22 ---- 2.1583860086471636
23 ---- 2.865198364020101
24 ---- 6.457951397444763
24 ---- 2.8464061660262128
25 ---- 4.751462405159283
26 ---- 16.664353050297613
26 ---- 6.433862464128575
26 ---- 8.90569527930927
26 ---- 2.3948438776920553
27 ---- 8.625154493499016
27 ---- 13.097583499300075
27 ---- 3.5102775257188883
28 ---- 1.8461247374915497
29 ---- 18.35043652870675
29 ---- 10.708249343242189
29 ---- 2.3460067597985903
30 ---- 21.54248963193387
30 ---- 2.796240194688435
31 ---- 3.373862552634251
32 ---- 9.973017265651706
32 ---- 6.0926832186982995
32 ---- 1.0011742340538425
33 ---- 3.0642351806835473
34 ---- 2.807411739205449
35 ---- 20.28118581063136
35 ---- 15.881630139889586
35 ---- 1.8328052344483383
36 ---- 1.5682347319653953
37 ---- 1.8780555342424192
38 ---- 4.3267589683233965
39 ---- 10.843732672072079

In [36]:
len(columns_to_be_kept)

39

In [37]:
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df["Approved_Flag"])

    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']

    f_stat, p_val = f_oneway(group_P1,group_P2,group_P3,group_P4)

    if p_val < 0.05:
        columns_to_be_kept_numerical.append(i)

In [38]:
len(columns_to_be_kept_numerical)

36

In [39]:
df.to_csv("cleaned_data.csv", index=False)